// Generated by CoffeeScript 1.6.3
var MySQL, prefix, _mysql;

_mysql = require('mysql');

prefix = ':';

MySQL = (function() {
  function MySQL(config) {
    this.pool = _mysql.createPool(config);
  }

  MySQL.prototype.query = function(sql, args, callback) {
    return this.pool.getConnection(function(err, connection) {
      var k, v;
      if (err) {
        console.log('Error when get con:' + err);
      }
      if (Object.prototype.toString.call(args) === '[object Array]') {
        console.log(sql);
        return connection.query(sql, args, function(err, rows) {
          connection.release();
          return callback(err, rows);
        });
      } else if (Object.prototype.toString.call(args) === '[object Object]') {
        for (k in args) {
          v = args[k];
          sql = sql.replace(prefix + k, "'" + v + "'");
        }
        console.log(sql);
        return connection.query(sql, function(err, rows) {
          connection.release();
          return callback(err, rows);
        });
      } else {
        callback = args;
        return connection.query(sql, function(err, rows) {
          connection.release();
          return callback(err, rows);
        });
      }
    });
  };

  MySQL.prototype.end = function() {
    return this.pool.end();
  };

  return MySQL;

})();

module.exports = MySQL;
