// Generated by CoffeeScript 1.7.1
var func;

func = [];

func['redis'] = require('./redis_cache');

func['memcache'] = require('./memcache_cache');

module.exports = function(config) {
  return new func[config.type](config.options);
};
