// Generated by CoffeeScript 1.6.3
var memcache, memcacheMethods;

memcache = require('memcached');

memcacheMethods = (function() {
  function memcacheMethods(config) {
    var serverString;
    serverString = "" + config.host + ":" + config.port;
    delete config.host;
    delete config.port;
    this.mem = new memcache(serverString, config.options);
  }

  memcacheMethods.prototype.set = function(key, row, ttl, callback) {
    return this.mem.set(key, row, ttl, function(err) {
      if (callback) {
        return callback(err, null);
      }
    });
  };

  memcacheMethods.prototype.get = function(keys, callback) {
    return this.mem.getMulti(keys, function(err, data) {
      return callback(err, data);
    });
  };

  memcacheMethods.prototype.del = function(key, callback) {
    return this.mem.del(key, function(err) {
      if (callback) {
        return callback(err, null);
      }
    });
  };

  memcacheMethods.prototype.end = function() {
    return this.mem.end();
  };

  return memcacheMethods;

})();

module.exports = memcacheMethods;
