// Generated by CoffeeScript 2.5.1
var _, memcache, memcacheMethods, toType;

memcache = require('memcached');

_ = require('lodash');

({toType} = require('../utils'));

memcacheMethods = class memcacheMethods {
  constructor(_config) {
    var config, serverString;
    config = _.cloneDeep(_config);
    serverString = `${config.host}:${config.port}`;
    delete config.host;
    delete config.port;
    this.mem = new memcache(serverString, config.options);
  }

  // if Object.keys(config).length isnt 0
  //   # console.log config
  //   @mem = new memcache serverString, config.options
  // else
  //   console.log '空了'
  //   @mem = new memcache serverString
  set(key, row, ttl, callback) {
    var _ttl;
    _ttl = ttl;
    if (callback == null) {
      _ttl = 0;
      callback = ttl;
    }
    return this.mem.set(key, row, _ttl, function(err) {
      if (callback) {
        return callback(err, null);
      }
    });
  }

  get(keys, callback) {
    var k;
    if (toType(keys) === 'string') {
      k = [];
      k.push(keys);
      return this.mem.getMulti(k, function(err, data) {
        return callback(err, data);
      });
    } else {
      return this.mem.getMulti(keys, function(err, data) {
        return callback(err, data);
      });
    }
  }

  del(key, callback) {
    return this.mem.del(key, function(err) {
      if (callback) {
        return callback(err, null);
      }
    });
  }

  end() {
    return this.mem.end();
  }

};

module.exports = memcacheMethods;
